title: "bl-rd 🖖"
author: "Bill Reid"

# animations config
page_animations_path: "assets/js/animations"

# lines background on home page
home_background: true

# how many "latest" posts/things should be on the home page
max_home_latest: 3

# include "notes" in "latest" section of home page?
home_latest_notes: false

# notes config
notes_overflow_size: 75

# show the copyright thing-y in the footer?
show_copyright_date: false
# can't seem to access the date dynamically 😢
copyright_date: 2021

# tags config
valid_tags: [
  "web",
  "indieweb",
  "javascript",
  "css",
  "codepen",
  "html",
  "rust",
  "games",
  "music"
]

# Main javascript files to include
scripts: [
  "assets/js/lib/text.js",
  "assets/js/components/back-to-top.js"
]