baseURL = "https://www.bl-rd.dev/"
languageCode = "en-gb"
title = "Bill's Website"
newContentEditor = "code"
theme = "test"
[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "swapoff"
    tabWidth = 2
