title: "bl-rd 🖖"
author: "Bill Reid"

# animations config
page_animations_path: "assets/js/animations"

# lines background on home page
home_background: true

# Main javascript files to include
scripts: [
  "assets/js/lib/text.js",
  "assets/js/components/back-to-top.js"
]